@baseUrl = http://localhost:8080

### Create ingredient
POST {{baseUrl}}/ingredients
Content-Type: application/json

{
    "name": "Джин",
    "description": "London dry gin",
    "unit_measurement": "мл",
    "abv": "крепкий",
    "ingredient_type": "крепкая часть"
}

### Get ingredient by id
GET {{baseUrl}}/ingredients/1

### Partial update ingredient
PATCH {{baseUrl}}/ingredients/1
Content-Type: application/json

{
    "name": "Джин London Dry",
    "description": "Обновлённое описание"
}

### Delete ingredient
DELETE {{baseUrl}}/ingredients/1

### Set ingredient icon
PUT {{baseUrl}}/ingredients/1/icon
Content-Type: application/octet-stream

< ./icon.png
